# Generated by Django 3.0.6 on 2020-06-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.ManyToManyField(to='AdminSide.Department')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminSide.Level')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.Level'),
        ),
    ]
